// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbad.xtrak.domain;

import com.nbad.xtrak.domain.Expense;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Expense_Roo_Configurable {
    
    declare @type: Expense: @Configurable;
    
}
