// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbad.xtrak.domain;

import com.nbad.xtrak.domain.Expense;
import com.nbad.xtrak.domain.ExpenseDataOnDemand;
import com.nbad.xtrak.domain.ExpenseDetails;
import com.nbad.xtrak.domain.ExpenseDetailsDataOnDemand;
import com.nbad.xtrak.domain.Login;
import com.nbad.xtrak.domain.LoginDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ExpenseDetailsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ExpenseDetailsDataOnDemand: @Component;
    
    private Random ExpenseDetailsDataOnDemand.rnd = new SecureRandom();
    
    private List<ExpenseDetails> ExpenseDetailsDataOnDemand.data;
    
    @Autowired
    ExpenseDataOnDemand ExpenseDetailsDataOnDemand.expenseDataOnDemand;
    
    @Autowired
    LoginDataOnDemand ExpenseDetailsDataOnDemand.loginDataOnDemand;
    
    public ExpenseDetails ExpenseDetailsDataOnDemand.getNewTransientExpenseDetails(int index) {
        ExpenseDetails obj = new ExpenseDetails();
        setCost(obj, index);
        setExpense(obj, index);
        setPaidFor(obj, index);
        return obj;
    }
    
    public void ExpenseDetailsDataOnDemand.setCost(ExpenseDetails obj, int index) {
        Double cost = new Integer(index).doubleValue();
        obj.setCost(cost);
    }
    
    public void ExpenseDetailsDataOnDemand.setExpense(ExpenseDetails obj, int index) {
        Expense expense = expenseDataOnDemand.getRandomExpense();
        obj.setExpense(expense);
    }
    
    public void ExpenseDetailsDataOnDemand.setPaidFor(ExpenseDetails obj, int index) {
        Login paidFor = loginDataOnDemand.getRandomLogin();
        obj.setPaidFor(paidFor);
    }
    
    public ExpenseDetails ExpenseDetailsDataOnDemand.getSpecificExpenseDetails(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ExpenseDetails obj = data.get(index);
        Long id = obj.getId();
        return ExpenseDetails.findExpenseDetails(id);
    }
    
    public ExpenseDetails ExpenseDetailsDataOnDemand.getRandomExpenseDetails() {
        init();
        ExpenseDetails obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ExpenseDetails.findExpenseDetails(id);
    }
    
    public boolean ExpenseDetailsDataOnDemand.modifyExpenseDetails(ExpenseDetails obj) {
        return false;
    }
    
    public void ExpenseDetailsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ExpenseDetails.findExpenseDetailsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ExpenseDetails' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ExpenseDetails>();
        for (int i = 0; i < 10; i++) {
            ExpenseDetails obj = getNewTransientExpenseDetails(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
