// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbad.xtrak.domain;

import com.nbad.xtrak.domain.ExpenseDetails;
import com.nbad.xtrak.domain.ExpenseDetailsDataOnDemand;
import com.nbad.xtrak.domain.ExpenseDetailsIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ExpenseDetailsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ExpenseDetailsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ExpenseDetailsIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ExpenseDetailsIntegrationTest: @Transactional;
    
    @Autowired
    ExpenseDetailsDataOnDemand ExpenseDetailsIntegrationTest.dod;
    
    @Test
    public void ExpenseDetailsIntegrationTest.testCountExpenseDetailses() {
        Assert.assertNotNull("Data on demand for 'ExpenseDetails' failed to initialize correctly", dod.getRandomExpenseDetails());
        long count = ExpenseDetails.countExpenseDetailses();
        Assert.assertTrue("Counter for 'ExpenseDetails' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ExpenseDetailsIntegrationTest.testFindExpenseDetails() {
        ExpenseDetails obj = dod.getRandomExpenseDetails();
        Assert.assertNotNull("Data on demand for 'ExpenseDetails' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExpenseDetails' failed to provide an identifier", id);
        obj = ExpenseDetails.findExpenseDetails(id);
        Assert.assertNotNull("Find method for 'ExpenseDetails' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ExpenseDetails' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ExpenseDetailsIntegrationTest.testFindAllExpenseDetailses() {
        Assert.assertNotNull("Data on demand for 'ExpenseDetails' failed to initialize correctly", dod.getRandomExpenseDetails());
        long count = ExpenseDetails.countExpenseDetailses();
        Assert.assertTrue("Too expensive to perform a find all test for 'ExpenseDetails', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ExpenseDetails> result = ExpenseDetails.findAllExpenseDetailses();
        Assert.assertNotNull("Find all method for 'ExpenseDetails' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ExpenseDetails' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ExpenseDetailsIntegrationTest.testFindExpenseDetailsEntries() {
        Assert.assertNotNull("Data on demand for 'ExpenseDetails' failed to initialize correctly", dod.getRandomExpenseDetails());
        long count = ExpenseDetails.countExpenseDetailses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ExpenseDetails> result = ExpenseDetails.findExpenseDetailsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ExpenseDetails' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ExpenseDetails' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ExpenseDetailsIntegrationTest.testFlush() {
        ExpenseDetails obj = dod.getRandomExpenseDetails();
        Assert.assertNotNull("Data on demand for 'ExpenseDetails' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExpenseDetails' failed to provide an identifier", id);
        obj = ExpenseDetails.findExpenseDetails(id);
        Assert.assertNotNull("Find method for 'ExpenseDetails' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyExpenseDetails(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ExpenseDetails' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExpenseDetailsIntegrationTest.testMergeUpdate() {
        ExpenseDetails obj = dod.getRandomExpenseDetails();
        Assert.assertNotNull("Data on demand for 'ExpenseDetails' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExpenseDetails' failed to provide an identifier", id);
        obj = ExpenseDetails.findExpenseDetails(id);
        boolean modified =  dod.modifyExpenseDetails(obj);
        Integer currentVersion = obj.getVersion();
        ExpenseDetails merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ExpenseDetails' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExpenseDetailsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ExpenseDetails' failed to initialize correctly", dod.getRandomExpenseDetails());
        ExpenseDetails obj = dod.getNewTransientExpenseDetails(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ExpenseDetails' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ExpenseDetails' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ExpenseDetails' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ExpenseDetailsIntegrationTest.testRemove() {
        ExpenseDetails obj = dod.getRandomExpenseDetails();
        Assert.assertNotNull("Data on demand for 'ExpenseDetails' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExpenseDetails' failed to provide an identifier", id);
        obj = ExpenseDetails.findExpenseDetails(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ExpenseDetails' with identifier '" + id + "'", ExpenseDetails.findExpenseDetails(id));
    }
    
}
