// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbad.xtrak.domain;

import com.nbad.xtrak.domain.ItemType;
import com.nbad.xtrak.domain.ItemTypeDataOnDemand;
import com.nbad.xtrak.domain.ItemTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ItemTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ItemTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ItemTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ItemTypeIntegrationTest: @Transactional;
    
    @Autowired
    ItemTypeDataOnDemand ItemTypeIntegrationTest.dod;
    
    @Test
    public void ItemTypeIntegrationTest.testCountItemTypes() {
        Assert.assertNotNull("Data on demand for 'ItemType' failed to initialize correctly", dod.getRandomItemType());
        long count = ItemType.countItemTypes();
        Assert.assertTrue("Counter for 'ItemType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ItemTypeIntegrationTest.testFindItemType() {
        ItemType obj = dod.getRandomItemType();
        Assert.assertNotNull("Data on demand for 'ItemType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ItemType' failed to provide an identifier", id);
        obj = ItemType.findItemType(id);
        Assert.assertNotNull("Find method for 'ItemType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ItemType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ItemTypeIntegrationTest.testFindAllItemTypes() {
        Assert.assertNotNull("Data on demand for 'ItemType' failed to initialize correctly", dod.getRandomItemType());
        long count = ItemType.countItemTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'ItemType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ItemType> result = ItemType.findAllItemTypes();
        Assert.assertNotNull("Find all method for 'ItemType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ItemType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ItemTypeIntegrationTest.testFindItemTypeEntries() {
        Assert.assertNotNull("Data on demand for 'ItemType' failed to initialize correctly", dod.getRandomItemType());
        long count = ItemType.countItemTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ItemType> result = ItemType.findItemTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ItemType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ItemType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ItemTypeIntegrationTest.testFlush() {
        ItemType obj = dod.getRandomItemType();
        Assert.assertNotNull("Data on demand for 'ItemType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ItemType' failed to provide an identifier", id);
        obj = ItemType.findItemType(id);
        Assert.assertNotNull("Find method for 'ItemType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyItemType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ItemType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ItemTypeIntegrationTest.testMergeUpdate() {
        ItemType obj = dod.getRandomItemType();
        Assert.assertNotNull("Data on demand for 'ItemType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ItemType' failed to provide an identifier", id);
        obj = ItemType.findItemType(id);
        boolean modified =  dod.modifyItemType(obj);
        Integer currentVersion = obj.getVersion();
        ItemType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ItemType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ItemTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ItemType' failed to initialize correctly", dod.getRandomItemType());
        ItemType obj = dod.getNewTransientItemType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ItemType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ItemType' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ItemType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ItemTypeIntegrationTest.testRemove() {
        ItemType obj = dod.getRandomItemType();
        Assert.assertNotNull("Data on demand for 'ItemType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ItemType' failed to provide an identifier", id);
        obj = ItemType.findItemType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ItemType' with identifier '" + id + "'", ItemType.findItemType(id));
    }
    
}
