// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbad.xtrak.domain;

import com.nbad.xtrak.domain.ItemType;
import com.nbad.xtrak.domain.ItemTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ItemTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ItemTypeDataOnDemand: @Component;
    
    private Random ItemTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<ItemType> ItemTypeDataOnDemand.data;
    
    public ItemType ItemTypeDataOnDemand.getNewTransientItemType(int index) {
        ItemType obj = new ItemType();
        setItemCode(obj, index);
        setItemDescription(obj, index);
        return obj;
    }
    
    public void ItemTypeDataOnDemand.setItemCode(ItemType obj, int index) {
        String itemCode = "itemCode_" + index;
        obj.setItemCode(itemCode);
    }
    
    public void ItemTypeDataOnDemand.setItemDescription(ItemType obj, int index) {
        String itemDescription = "itemDescription_" + index;
        obj.setItemDescription(itemDescription);
    }
    
    public ItemType ItemTypeDataOnDemand.getSpecificItemType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ItemType obj = data.get(index);
        Long id = obj.getId();
        return ItemType.findItemType(id);
    }
    
    public ItemType ItemTypeDataOnDemand.getRandomItemType() {
        init();
        ItemType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ItemType.findItemType(id);
    }
    
    public boolean ItemTypeDataOnDemand.modifyItemType(ItemType obj) {
        return false;
    }
    
    public void ItemTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ItemType.findItemTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ItemType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ItemType>();
        for (int i = 0; i < 10; i++) {
            ItemType obj = getNewTransientItemType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
