// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbad.xtrak.domain;

import com.nbad.xtrak.domain.Login;
import com.nbad.xtrak.domain.LoginDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect LoginDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LoginDataOnDemand: @Component;
    
    private Random LoginDataOnDemand.rnd = new SecureRandom();
    
    private List<Login> LoginDataOnDemand.data;
    
    public Login LoginDataOnDemand.getNewTransientLogin(int index) {
        Login obj = new Login();
        setActive(obj, index);
        setLastLogin(obj, index);
        setPassword(obj, index);
        setRole(obj, index);
        setUsername(obj, index);
        return obj;
    }
    
    public void LoginDataOnDemand.setActive(Login obj, int index) {
        Boolean active = Boolean.TRUE;
        obj.setActive(active);
    }
    
    public void LoginDataOnDemand.setLastLogin(Login obj, int index) {
        Date lastLogin = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setLastLogin(lastLogin);
    }
    
    public void LoginDataOnDemand.setPassword(Login obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public void LoginDataOnDemand.setRole(Login obj, int index) {
        String role = "role_" + index;
        obj.setRole(role);
    }
    
    public void LoginDataOnDemand.setUsername(Login obj, int index) {
        String username = "username_" + index;
        obj.setUsername(username);
    }
    
    public Login LoginDataOnDemand.getSpecificLogin(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Login obj = data.get(index);
        Long id = obj.getId();
        return Login.findLogin(id);
    }
    
    public Login LoginDataOnDemand.getRandomLogin() {
        init();
        Login obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Login.findLogin(id);
    }
    
    public boolean LoginDataOnDemand.modifyLogin(Login obj) {
        return false;
    }
    
    public void LoginDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Login.findLoginEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Login' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Login>();
        for (int i = 0; i < 10; i++) {
            Login obj = getNewTransientLogin(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
