// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbad.xtrak.domain;

import com.nbad.xtrak.domain.Login;
import com.nbad.xtrak.domain.LoginDataOnDemand;
import com.nbad.xtrak.domain.Payments;
import com.nbad.xtrak.domain.PaymentsDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PaymentsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PaymentsDataOnDemand: @Component;
    
    private Random PaymentsDataOnDemand.rnd = new SecureRandom();
    
    private List<Payments> PaymentsDataOnDemand.data;
    
    @Autowired
    LoginDataOnDemand PaymentsDataOnDemand.loginDataOnDemand;
    
    public Payments PaymentsDataOnDemand.getNewTransientPayments(int index) {
        Payments obj = new Payments();
        setAmount(obj, index);
        setPaidBy(obj, index);
        setPaidDate(obj, index);
        setPaidTo(obj, index);
        return obj;
    }
    
    public void PaymentsDataOnDemand.setAmount(Payments obj, int index) {
        Double amount = new Integer(index).doubleValue();
        obj.setAmount(amount);
    }
    
    public void PaymentsDataOnDemand.setPaidBy(Payments obj, int index) {
        Login paidBy = loginDataOnDemand.getRandomLogin();
        obj.setPaidBy(paidBy);
    }
    
    public void PaymentsDataOnDemand.setPaidDate(Payments obj, int index) {
        Date paidDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setPaidDate(paidDate);
    }
    
    public void PaymentsDataOnDemand.setPaidTo(Payments obj, int index) {
        Login paidTo = loginDataOnDemand.getRandomLogin();
        obj.setPaidTo(paidTo);
    }
    
    public Payments PaymentsDataOnDemand.getSpecificPayments(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Payments obj = data.get(index);
        Long id = obj.getId();
        return Payments.findPayments(id);
    }
    
    public Payments PaymentsDataOnDemand.getRandomPayments() {
        init();
        Payments obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Payments.findPayments(id);
    }
    
    public boolean PaymentsDataOnDemand.modifyPayments(Payments obj) {
        return false;
    }
    
    public void PaymentsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Payments.findPaymentsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Payments' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Payments>();
        for (int i = 0; i < 10; i++) {
            Payments obj = getNewTransientPayments(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
