// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbad.xtrak.domain;

import com.nbad.xtrak.domain.Payments;
import com.nbad.xtrak.domain.PaymentsDataOnDemand;
import com.nbad.xtrak.domain.PaymentsIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PaymentsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PaymentsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PaymentsIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PaymentsIntegrationTest: @Transactional;
    
    @Autowired
    PaymentsDataOnDemand PaymentsIntegrationTest.dod;
    
    @Test
    public void PaymentsIntegrationTest.testCountPaymentses() {
        Assert.assertNotNull("Data on demand for 'Payments' failed to initialize correctly", dod.getRandomPayments());
        long count = Payments.countPaymentses();
        Assert.assertTrue("Counter for 'Payments' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PaymentsIntegrationTest.testFindPayments() {
        Payments obj = dod.getRandomPayments();
        Assert.assertNotNull("Data on demand for 'Payments' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Payments' failed to provide an identifier", id);
        obj = Payments.findPayments(id);
        Assert.assertNotNull("Find method for 'Payments' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Payments' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PaymentsIntegrationTest.testFindAllPaymentses() {
        Assert.assertNotNull("Data on demand for 'Payments' failed to initialize correctly", dod.getRandomPayments());
        long count = Payments.countPaymentses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Payments', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Payments> result = Payments.findAllPaymentses();
        Assert.assertNotNull("Find all method for 'Payments' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Payments' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PaymentsIntegrationTest.testFindPaymentsEntries() {
        Assert.assertNotNull("Data on demand for 'Payments' failed to initialize correctly", dod.getRandomPayments());
        long count = Payments.countPaymentses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Payments> result = Payments.findPaymentsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Payments' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Payments' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PaymentsIntegrationTest.testFlush() {
        Payments obj = dod.getRandomPayments();
        Assert.assertNotNull("Data on demand for 'Payments' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Payments' failed to provide an identifier", id);
        obj = Payments.findPayments(id);
        Assert.assertNotNull("Find method for 'Payments' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPayments(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Payments' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PaymentsIntegrationTest.testMergeUpdate() {
        Payments obj = dod.getRandomPayments();
        Assert.assertNotNull("Data on demand for 'Payments' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Payments' failed to provide an identifier", id);
        obj = Payments.findPayments(id);
        boolean modified =  dod.modifyPayments(obj);
        Integer currentVersion = obj.getVersion();
        Payments merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Payments' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PaymentsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Payments' failed to initialize correctly", dod.getRandomPayments());
        Payments obj = dod.getNewTransientPayments(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Payments' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Payments' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Payments' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PaymentsIntegrationTest.testRemove() {
        Payments obj = dod.getRandomPayments();
        Assert.assertNotNull("Data on demand for 'Payments' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Payments' failed to provide an identifier", id);
        obj = Payments.findPayments(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Payments' with identifier '" + id + "'", Payments.findPayments(id));
    }
    
}
