// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbad.xtrak.web.converter;

import com.nbad.xtrak.web.converter.ItemTypeConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ItemTypeConverter_Roo_Configurable {
    
    declare @type: ItemTypeConverter: @Configurable;
    
}
