// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbad.xtrak.web;

import com.nbad.xtrak.web.ExpenseDetailsBean;
import java.io.Serializable;

privileged aspect ExpenseDetailsBean_Roo_Serializable {
    
    declare parents: ExpenseDetailsBean implements Serializable;
    
    private static final long ExpenseDetailsBean.serialVersionUID = 1L;
    
}
