// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbad.xtrak.web;

import com.nbad.xtrak.web.ExpenseBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ExpenseBean_Roo_Configurable {
    
    declare @type: ExpenseBean: @Configurable;
    
}
