// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbad.xtrak.web;

import com.nbad.xtrak.web.PaymentsBean;
import java.io.Serializable;

privileged aspect PaymentsBean_Roo_Serializable {
    
    declare parents: PaymentsBean implements Serializable;
    
    private static final long PaymentsBean.serialVersionUID = 1L;
    
}
